[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "autonomy"
version = "0.1.0"
description = "Machine learning components for sunnypilot"
dependencies = [
    "numpy >=2.0",
    "matplotlib",
    "onnx >= 1.14.0",
    "onnxruntime",
    "opencv-python-headless",
    "dearpygui>=2.1.0",
    "requests",
    "torch",
    "torchvision",
    "metadrive-simulator @ https://github.com/commaai/metadrive/releases/download/MetaDrive-minimal-0.4.2.4/metadrive_simulator-0.4.2.4-py3-none-any.whl",
    "hypothesis ==6.47.*",
    "mypy",
    "panda3d",
    "pytest",
    "pytest-cpp",
    "pytest-subtests",
    "pytest-xdist @ git+https://github.com/sshane/pytest-xdist@2b4372bd62699fb412c4fe2f95bf9f01bd2018da",
    "pytest-timeout",
    "pytest-randomly",
    "pytest-asyncio",
    "pytest-mock",
    "pytest-repeat",
    "ruff",
    "codespell",
    "pre-commit-hooks",
]
