[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "autonomy"
version = "0.1.0"
description = "Machine learning components for sunnypilot"
requires-python = ">=3.12"
dependencies = [
    "datasets == 4.0.0",
    "dearpygui >= 2.1.0",
    "hypothesis == 6.47.*",
    "matplotlib",
    "numpy >= 2.0",
    "onnx >= 1.14.0",
    "onnxruntime",
    "opencv-python-headless",
    "panda3d",
    "requests",
    "torch",
    "torchvision",
    "ultralytics",
]

[project.optional-dependencies]
testing = [
    "codespell",
    "mypy",
    "pre-commit-hooks",
    "pytest",
    "pytest-cpp",
    "pytest-subtests",
    "pytest-xdist @ git+https://github.com/sshane/pytest-xdist@2b4372bd62699fb412c4fe2f95bf9f01bd2018da",
    "pytest-timeout",
    "pytest-randomly",
    "pytest-asyncio",
    "pytest-mock",
    "pytest-repeat",
    "ruff",
]
simulator = [
    "metadrive-simulator @ https://github.com/commaai/metadrive/releases/download/MetaDrive-minimal-0.4.2.4/metadrive_simulator-0.4.2.4-py3-none-any.whl",
]
